name: Deploy@DEV

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp://unmus.de/unmus/dev/wordpress/wp-content/themes/huhu
          username: ${{ secrets.FTP_USER_GUTHUBDEPLOY }}
          password: ${{ secrets.FTP_PASSWORD_GITHUBDEPLOY }}
